// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dquzjvmabrbauctrfqls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxdXpqdm1hYnJiYXVjdHJmcWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTc5NjQsImV4cCI6MjA2Mzk5Mzk2NH0.4ivuNgRDi6JSsBKmC_L-ivf314Uw_dhYUo3NSdCFKEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);